name: Cleanup stuck deployments
on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - name: Deactivate only in-progress deployments for production@master
        shell: bash
        env:
          ENV_NAME: production
          REF_NAME: refs/heads/master
        run: |
          set -euo pipefail
          echo "Repo: $GITHUB_REPOSITORY"
          echo "Env:  $ENV_NAME"
          echo "Ref:  $REF_NAME"

          gh api -H "Accept: application/vnd.github+json" \
            repos/$GITHUB_REPOSITORY/deployments \
            --paginate -f environment="$ENV_NAME" -f ref="$REF_NAME" \
          | jq -r '.[].id' | while read -r DEPLOY_ID; do
              LAST_STATE=$(gh api -H "Accept: application/vnd.github+json" \
                repos/$GITHUB_REPOSITORY/deployments/$DEPLOY_ID/statuses \
                -f per_page=1 | jq -r '.[0].state // "none"')

              if [[ "$LAST_STATE" == "in_progress" || "$LAST_STATE" == "pending" || "$LAST_STATE" == "queued" ]]; then
                echo "→ Deactivating deployment $DEPLOY_ID (was: $LAST_STATE)"
                gh api -H "Accept: application/vnd.github+json" \
                  repos/$GITHUB_REPOSITORY/deployments/$DEPLOY_ID/statuses \
                  -f state=inactive >/dev/null
              else
                echo "✓ Skip $DEPLOY_ID (state: $LAST_STATE)"
              fi
            done

          echo "Done."
